### ISSUE TITLE
[5356] Error loading Python lib

### ISSUE THREAD

**Issue by akvotil** [eSwapping/ESWAP-Limit-Order-Bot#4]
MacOS 10.15.7 (latest supported for my hardware). Get this error. How to fix?

[5356] Error loading Python lib '/var/folders/pv/wpc3yf3j0nncr7xn1qgthymw0000gn/T/_MEIJrj3tS/Python': dlopen: dlopen(/var/folders/pv/wpc3yf3j0nncr7xn1qgthymw0000gn/T/_MEIJrj3tS/Python, 10): Symbol not found: _preadv
  Referenced from: /var/folders/pv/wpc3yf3j0nncr7xn1qgthymw0000gn/T/_MEIJrj3tS/Python (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/pv/wpc3yf3j0nncr7xn1qgthymw0000gn/T/_MEIJrj3tS/Python

**Comment by Filip722** [comment]
Looks like the MacOS version is not supported. Unfortunately i cannot test it (so fix it) as i do not own such a machine.

Your best option is to use a Virtual Machine (VirtualBox, Parallels) with Linux Ubuntu/Mint.
